import { commonProps } from "../../utils";

export const dialogProps = {
  show: Boolean,
  title: String,
  message: String,
  theme: { type: String, default: "default" },
  confirmButtonId: String,
  className: String,
  customStyle: commonProps.customStyle,
  asyncClose: Boolean,
  messageAlign: String,
  beforeClose: Function,
  overlayStyle: commonProps.customStyle,
  useSlot: Boolean,
  useTitleSlot: Boolean,
  useConfirmButtonSlot: Boolean,
  useCancelButtonSlot: Boolean,
  showCancelButton: Boolean,
  closeOnClickOverlay: Boolean,
  confirmButtonOpenType: String,
  width: [String, Number],
  zIndex: { type: Number, default: 2000 },
  confirmButtonText: { type: String, default: "确认" },
  cancelButtonText: { type: String, default: "取消" },
  confirmButtonColor: { type: String, default: "#ee0a24" },
  cancelButtonColor: { type: String, default: "#323233" },
  showConfirmButton: { type: Boolean, default: true },
  overlay: { type: Boolean, default: true },
  transition: { type: String, default: "scale" },
  rootPortal: { type: Boolean, default: false },
  lang: String,
  businessId: String,
  sessionFrom: String,
  sendMessageTitle: String,
  sendMessagePath: String,
  sendMessageImg: String,
  showMessageCard: Boolean,
  appParameter: String,
};
