declare module "vue" {
  // Helper for Volar
  export interface GlobalComponents {
    VanActionSheet: typeof import("./components/van-action-sheet/van-action-sheet.vue")["default"];
    VanArea: typeof import("./components/van-area/van-area.vue")["default"];
    VanButton: typeof import("./components/van-button/van-button.vue")["default"];
    VanCalendar: typeof import("./components/van-calendar/van-calendar.vue")["default"];
    VanCard: typeof import("./components/van-card/van-card.vue")["default"];
    VanCell: typeof import("./components/van-cell/van-cell.vue")["default"];
    VanCellGroup: typeof import("./components/van-cell-group/van-cell-group.vue")["default"];
    VanCheckbox: typeof import("./components/van-checkbox/van-checkbox.vue")["default"];
    VanCheckboxGroup: typeof import("./components/van-checkbox-group/van-checkbox-group.vue")["default"];
    VanCircle: typeof import("./components/van-circle/van-circle.vue")["default"];
    VanCol: typeof import("./components/van-col/van-col.vue")["default"];
    VanCollapse: typeof import("./components/van-collapse/van-collapse.vue")["default"];
    VanCollapseItem: typeof import("./components/van-collapse-item/van-collapse-item.vue")["default"];
    VanConfigProvider: typeof import("./components/van-config-provider/van-config-provider.vue")["default"];
    VanCountDown: typeof import("./components/van-count-down/van-count-down.vue")["default"];
    VanDatetimePicker: typeof import("./components/van-datetime-picker/van-datetime-picker.vue")["default"];
    VanDialog: typeof import("./components/van-dialog/van-dialog.vue")["default"];
    VanDivider: typeof import("./components/van-divider/van-divider.vue")["default"];
    VanDropdownItem: typeof import("./components/van-dropdown-item/van-dropdown-item.vue")["default"];
    VanDropdownMenu: typeof import("./components/van-dropdown-menu/van-dropdown-menu.vue")["default"];
    VanEmpty: typeof import("./components/van-empty/van-empty.vue")["default"];
    VanField: typeof import("./components/van-field/van-field.vue")["default"];
    VanGoodsAction: typeof import("./components/van-goods-action/van-goods-action.vue")["default"];
    VanGoodsActionButton: typeof import("./components/van-goods-action-button/van-goods-action-button.vue")["default"];
    VanGoodsActionIcon: typeof import("./components/van-goods-action-icon/van-goods-action-icon.vue")["default"];
    VanGrid: typeof import("./components/van-grid/van-grid.vue")["default"];
    VanGridItem: typeof import("./components/van-grid-item/van-grid-item.vue")["default"];
    VanIcon: typeof import("./components/van-icon/van-icon.vue")["default"];
    VanImage: typeof import("./components/van-image/van-image.vue")["default"];
    VanIndexAnchor: typeof import("./components/van-index-anchor/van-index-anchor.vue")["default"];
    VanIndexBar: typeof import("./components/van-index-bar/van-index-bar.vue")["default"];
    VanInfo: typeof import("./components/van-info/van-info.vue")["default"];
    VanLoading: typeof import("./components/van-loading/van-loading.vue")["default"];
    VanNavBar: typeof import("./components/van-nav-bar/van-nav-bar.vue")["default"];
    VanNotify: typeof import("./components/van-notify/van-notify.vue")["default"];
    VanOverlay: typeof import("./components/van-overlay/van-overlay.vue")["default"];
    VanPanel: typeof import("./components/van-panel/van-panel.vue")["default"];
    VanPicker: typeof import("./components/van-picker/van-picker.vue")["default"];
    VanPickerColumn: typeof import("./components/van-picker-column/van-picker-column.vue")["default"];
    VanPopup: typeof import("./components/van-popup/van-popup.vue")["default"];
    VanProgress: typeof import("./components/van-progress/van-progress.vue")["default"];
    VanRadio: typeof import("./components/van-radio/van-radio.vue")["default"];
    VanRadioGroup: typeof import("./components/van-radio-group/van-radio-group.vue")["default"];
    VanRate: typeof import("./components/van-rate/van-rate.vue")["default"];
    VanRow: typeof import("./components/van-row/van-row.vue")["default"];
    VanSearch: typeof import("./components/van-search/van-search.vue")["default"];
    VanShareSheet: typeof import("./components/van-share-sheet/van-share-sheet.vue")["default"];
    VanSidebar: typeof import("./components/van-sidebar/van-sidebar.vue")["default"];
    VanSidebarItem: typeof import("./components/van-sidebar-item/van-sidebar-item.vue")["default"];
    VanSkeleton: typeof import("./components/van-skeleton/van-skeleton.vue")["default"];
    VanSlider: typeof import("./components/van-slider/van-slider.vue")["default"];
    VanStep: typeof import("./components/van-stepper/van-stepper.vue")["default"];
    VanStepper: typeof import("./components/van-stepper/van-stepper.vue")["default"];
    VanSteps: typeof import("./components/van-steps/van-steps.vue")["default"];
    VanSticky: typeof import("./components/van-sticky/van-sticky.vue")["default"];
    VanSubmitBar: typeof import("./components/van-submit-bar/van-submit-bar.vue")["default"];
    VanSwipeCell: typeof import("./components/van-swipe-cell/van-swipe-cell.vue")["default"];
    VanSwitch: typeof import("./components/van-switch/van-switch.vue")["default"];
    VanTab: typeof import("./components/van-tab/van-tab.vue")["default"];
    VanTabbar: typeof import("./components/van-tabbar/van-tabbar.vue")["default"];
    VanTabbarItem: typeof import("./components/van-tabbar-item/van-tabbar-item.vue")["default"];
    VanTabs: typeof import("./components/van-tabs/van-tabs.vue")["default"];
    VanTag: typeof import("./components/van-tag/van-tag.vue")["default"];
    VanToast: typeof import("./components/van-toast/van-toast.vue")["default"];
    VanTransition: typeof import("./components/van-transition/van-transition.vue")["default"];
    VanTreeSelect: typeof import("./components/van-tree-select/van-tree-select.vue")["default"];
    VanUploader: typeof import("./components/van-uploader/van-uploader.vue")["default"];
  }
}

export {};
